name: Docker

on:
  push:
    branches: [master]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=sha
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
